import { cp, mkdir, writeFile } from "node:fs/promises";
import { parse as parseToml } from "smol-toml";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { CloudConfigSchema, isMcVersion, type CloudConfig } from "@cloud/schema";
import { renderCloudToml } from "../render/config.ts";
import { resolveProvider } from "../ai/provider.ts";
import { runWizard } from "../ai/wizard.ts";
import { latestVersion } from "../versions.ts";
import { ask, c, choose, confirm, fail, info, sym, warn } from "../ui.ts";
import { BlueprintError, freePort, loadBlueprint, networkName, type Blueprint } from "../blueprint.ts";
import { editCloudToml } from "../edit.ts";
import { withVersion } from "../version.ts";
import { CONFIG_FILE } from "../config.ts";
import { isWindows, isOnWindowsDrive, platformNotes } from "../platform.ts";
import { hasFlag, optionValue } from "../args.ts";

export async function init(argv: string[]): Promise<void> {
  const root = process.cwd();
  if (existsSync(join(root, CONFIG_FILE))) {
    fail(`${CONFIG_FILE} already exists here. Edit it, or delete it first.`);
  }

  const manual = hasFlag(argv, "--manual");
  const promptArg = optionValue(argv, "--prompt");
  const from = optionValue(argv, "--from");
  const versionArg = optionValue(argv, "--version");
  if (!from && (versionArg || optionValue(argv, "--name") || optionValue(argv, "--port"))) {
    fail("--version, --name and --port go with --from <blueprint>.");
  }

  let cfg: CloudConfig;
  let toml: string | null = null;
  let blueprint: Blueprint | null = null;
  const provider = manual || from ? null : await resolveProvider();

  if (from) {
    ({ cfg, toml, blueprint } = await fromBlueprint(from, argv, root));
  } else if (provider) {
    const prompt =
      promptArg ??
      (await ask(
        `${c.cyan("?")} Describe the network you want:\n ${c.dim(
          "e.g. velocity proxy, a paper lobby and a paper survival server",
        )}\n `,
      ));
    if (!prompt.trim()) fail("no description given.");
    cfg = await runWizard(provider, prompt);
  } else {
    if (!manual) {
      info(
        c.dim(
          "No AI provider configured — using the manual wizard.\n" +
            "  (Set ANTHROPIC_API_KEY or CLOUD_AI_PROVIDER=ollama for the conversational one.)\n",
        ),
      );
    }
    cfg = await manualWizard();
  }

  // Bind mounts cross the host<->VM filesystem bridge on Docker Desktop, which
  // is slow enough to stutter a Minecraft world. Default to a named volume
  // there, but record the choice in cloud.toml so the config still fully
  // determines the output.
  if (!blueprint && preferVolume(root, cfg)) {
    cfg = { ...cfg, network: { ...cfg.network, storage: "volume" } };
  }

  const notes = platformNotes(root);
  if (notes.length) {
    info("");
    for (const n of notes) info(c.dim(`  ${n}`));
  }

  toml ??= renderCloudToml(cfg);
  info("");
  info(c.bold(`${CONFIG_FILE}`));
  info(toml.split("\n").map((l) => c.dim("  ") + l).join("\n"));

  if (!(await confirm("Write this config?", true))) {
    info("Aborted. Nothing written.");
    return;
  }

  await writeFile(join(root, CONFIG_FILE), toml, "utf8");
  await mkdir(join(root, "templates"), { recursive: true });
  if (blueprint?.templatesDir) {
    // The blueprint's templates are part of what makes it that setup.
    await cp(blueprint.templatesDir, join(root, "templates"), { recursive: true });
    info(`${c.green(sym.ok)} copied templates/ from ${blueprint.source}`);
  }
  await writeFile(
    join(root, ".gitignore"),
    [
      "# Secrets.",
      ".env",
      "proxy/forwarding.secret",
      "",
      "# Worlds and server data.",
      "data/",
      "",
      "# GENERATED by `cloud apply`. cloud.toml is the source of truth;",
      "# committing these invites someone to edit them.",
      "docker-compose.yml",
      "proxy/velocity.toml",
      "proxy/config.yml",
      "proxy/patches/",
      "",
    ].join("\n"),
    "utf8",
  );

  info("");
  info(`${c.green(sym.ok)} wrote ${CONFIG_FILE}`);
  info(`  next: ${c.bold("cloud apply")}`);
  if (cfg.network.domain) {
    info("");
    info(c.dim("  DNS, so players can omit the port:"));
    info(
      c.dim(
        `    _minecraft._tcp.${cfg.network.domain}. 300 IN SRV 0 5 ${cfg.network.entry_port} ${cfg.network.domain}.`,
      ),
    );
    info(c.dim(`    ${cfg.network.domain}. 300 IN A <your server ip>`));
    info(
      c.dim(
        "  On Cloudflare this record must be DNS-only (grey cloud). The proxy\n" +
          "  does not carry Minecraft traffic.",
      ),
    );
  }
}

async function manualWizard(): Promise<CloudConfig> {
  const version = await latestVersion();

  const name = await ask(`${c.cyan("?")} Network name`, "network");
  const entry = await ask(`${c.cyan("?")} Port players connect to`, "25565");
  const motd = await ask(`${c.cyan("?")} MOTD`, "A Minecraft Network");
  const mc = await ask(`${c.cyan("?")} Minecraft version`, version);

  const groups: Record<string, unknown> = {};
  info("");
  info(c.dim("  Now the servers. Leave the name blank when you are done."));
  info(c.dim("  The first one becomes the lobby players land on."));

  let first = true;
  for (;;) {
    const gname = await ask(
      `${c.cyan("?")} Server name${first ? "" : " (blank to finish)"}`,
      first ? "lobby" : "",
    );
    if (!gname) break;
    const memory = await ask(`  ${c.dim("memory")}`, first ? "2G" : "4G");
    const kind = await choose(
      `  ${c.dim("what kind?")}`,
      [
        "pooled (lobbies, minigames — can run several instances)",
        "single (survival, SMP — one instance, files under data/ to browse)",
      ],
      first ? 0 : 1,
    );
    // A pooled group was offered as "can run several instances" and then
    // always written with one — no failover, nothing for a rolling restart to
    // cycle. Ask, and default to two: the smallest group that survives losing
    // an instance.
    let min = 1;
    if (kind.startsWith("pooled")) {
      for (;;) {
        const n = Number(await ask(`  ${c.dim("instances")}`, "2"));
        if (Number.isInteger(n) && n >= 1 && n <= 50) {
          min = n;
          break;
        }
        info(c.yellow("  a whole number from 1 to 50"));
      }
    }
    groups[gname] = {
      software: "paper",
      version: mc,
      memory,
      min,
      fallback: first,
      static: kind.startsWith("single"),
      plugins: [],
      env: {},
    };
    first = false;
  }

  if (!Object.keys(groups).length) fail("no servers defined.");

  const parsed = CloudConfigSchema.safeParse({
    network: {
      name,
      entry_port: Number(entry),
      motd,
      forwarding: "modern",
      online: true,
    },
    // No version here on purpose: the schema's default is a pinned 3.x
    // release. "latest" resolves to a Velocity 4.x snapshot that needs
    // Java 25 and is a dev build — never the right default.
    proxy: { software: "velocity", memory: "512m" },
    groups,
  });
  if (!parsed.success) {
    fail(
      "that combination is not valid:\n" +
        parsed.error.issues
          .map((i) => `  ${i.path.join(".")}: ${i.message}`)
          .join("\n"),
    );
  }
  return parsed.data;
}

/**
 * Bind mounts cross the host<->VM filesystem bridge on Docker Desktop, which
 * is slow enough to stutter a Minecraft world. Default to a named volume
 * there, but record the choice in cloud.toml so the config still fully
 * determines the output.
 */
function preferVolume(root: string, cfg: CloudConfig): boolean {
  return (isWindows || isOnWindowsDrive(root)) && cfg.network.storage === "bind";
}

/**
 * A new project from a blueprint: its cloud.toml with the version, a name of
 * its own and a free port. Edited from the blueprint's text rather than
 * rendered fresh, so the comments that explain the setup come along.
 */
async function fromBlueprint(
  from: string,
  argv: string[],
  root: string,
): Promise<{ cfg: CloudConfig; toml: string; blueprint: Blueprint }> {
  const versionArg = optionValue(argv, "--version");
  const nameArg = optionValue(argv, "--name");
  const portArg = optionValue(argv, "--port");
  if (versionArg && !isMcVersion(versionArg)) {
    fail(`--version takes a Minecraft version, e.g. 1.21.10 or 26.2 — not "${versionArg}".`);
  }

  let blueprint: Blueprint;
  try {
    blueprint = await loadBlueprint(from);
  } catch (err) {
    if (err instanceof BlueprintError) fail(err.message);
    throw err;
  }
  let base: CloudConfig;
  try {
    base = CloudConfigSchema.parse(parseToml(blueprint.text));
  } catch (err) {
    fail(`${from} is not a valid cloud.toml:\n  ${(err as Error).message.split("\n")[0]}`);
  }

  const next = versionArg ? withVersion(base, versionArg) : structuredClone(base);
  next.network.name = nameArg ?? networkName(base.network.name, versionArg);
  next.network.entry_port = portArg ? Number(portArg) : await freePort(base.network.entry_port);
  if (preferVolume(root, next)) next.network.storage = "volume";

  const parsed = CloudConfigSchema.safeParse(next);
  if (!parsed.success) {
    fail(
      `that blueprint does not work${versionArg ? ` with ${versionArg}` : ""}:\n` +
        parsed.error.issues.map((i) => `  ${i.path.join(".")}: ${i.message}`).join("\n"),
    );
  }
  const cfg = parsed.data;

  info(`${c.bold("from")} ${blueprint.source}`);
  info(c.dim(`  name ${cfg.network.name} · port ${cfg.network.entry_port}` +
    (versionArg ? ` · every group on ${versionArg}` : "")));
  if (cfg.network.entry_port !== base.network.entry_port && !portArg) {
    info(c.dim(`  port ${base.network.entry_port} is taken here, so this network gets ${cfg.network.entry_port}`));
  }

  const edited = editCloudToml(blueprint.text, cfg);
  if (!edited.inPlace) {
    warn(`the blueprint is written in canonical form: ${edited.reason}.`);
  }
  return { cfg, toml: edited.text, blueprint };
}
