import {
  containerLimitMiB,
  fabricProxyLiteFor,
  javaFor,
  PROXY_COMPATIBLE_FORGE,
  proxyJavaFor,
  refSlug,
  runsPlugins,
} from "@cloud/schema";
import type { CloudConfig } from "../types.ts";
import { BUNGEEGUARD_JAR, proxyConfigFile, wiringFor } from "./forwarding.ts";

// The Java mapping lives in the schema, because validating an image pin needs
// it too. Re-exported so the renderer stays the place people look for it.
export { javaFor, proxyJavaFor };

const GENERATED =
  "# GENERATED by `cloud apply` — DO NOT EDIT.\n" +
  "# Source of truth is cloud.toml. Changes here are overwritten.\n";

// A pin already names its tag ("java21@sha256:..."), and validation has
// checked that tag is the derived one, so it replaces the tag wholesale.
function proxyImage(
  software: string,
  version: string,
  override?: number,
  pin?: string,
): string {
  // Velocity/Bungee/Waterfall all live in itzg/mc-proxy, selected by TYPE.
  // This is NOT the same image as the backends.
  return `itzg/mc-proxy:${pin ?? `java${override ?? proxyJavaFor(software, version)}`}`;
}

function serverImage(mcVersion: string, override?: number, pin?: string): string {
  return `itzg/minecraft-server:${pin ?? `java${override ?? javaFor(mcVersion)}`}`;
}

export type HangarPlatform = "PAPER" | "VELOCITY" | "WATERFALL";

/**
 * Hangar has no support in the itzg images, but its download URL is a pure
 * function of slug, version and platform — so a `hangar` reference becomes an
 * ordinary `PLUGINS` entry and needs nothing at container start.
 */
export function hangarUrl(ref: string, platform: HangarPlatform): string {
  const [slug, version] = ref.split(":");
  return `https://hangar.papermc.io/api/v1/projects/${slug}/versions/${version}/${platform}/download`;
}

/** Hangar's platform for a proxy: BungeeCord takes Waterfall builds. */
export function proxyHangarPlatform(software: string): HangarPlatform {
  return software === "velocity" ? "VELOCITY" : "WATERFALL";
}

/**
 * The plugin environment shared by the proxy and backends: URLs and Hangar
 * references both land in `PLUGINS`, Modrinth references in the image's own
 * resolver.
 */
function pluginEnv(
  source: { plugins: string[]; modrinth: string[]; hangar: string[] },
  platform: HangarPlatform,
  required: string[] = [],
): Record<string, string> {
  const env: Record<string, string> = {};
  // A required jar steps aside when the user already lists one with the same
  // file name — from a fork or a mirror. Two copies of one plugin make the
  // server refuse to load either.
  const fileName = (u: string) => u.split("/").pop()!.toLowerCase();
  const listed = new Set(source.plugins.map(fileName));
  const urls = [
    ...required.filter((u) => !listed.has(fileName(u))),
    ...source.plugins,
    ...source.hangar.map((r) => hangarUrl(r, platform)),
  ];
  if (urls.length) env.PLUGINS = urls.join(",");
  if (source.modrinth.length) {
    env.MODRINTH_PROJECTS = source.modrinth.join(",");
    // A plugin missing its library fails at load time the same way a bad
    // download does — a crash loop that never names the missing jar. The
    // image resolves required dependencies if asked; it is off by default.
    env.MODRINTH_DOWNLOAD_DEPENDENCIES = "required";
  }
  return env;
}

/**
 * A Fabric server behind Velocity.
 *
 * FabricProxy-Lite is what verifies Velocity's modern forwarding on Fabric,
 * and it reads its secret from the environment — so, unlike Paper, there is
 * no file to patch. It is installed from a pinned per-version table
 * (fabricProxyLiteFor) unless the group already lists its own, and it pulls
 * in Fabric API as its declared dependency.
 *
 * `plugins` URLs are mods here: the image downloads them into /data/mods.
 */
function fabricEnv(g: CloudConfig["groups"][string]): Record<string, string> {
  const env: Record<string, string> = {
    FABRIC_PROXY_SECRET: "${FORWARDING_SECRET:?run `cloud apply` to generate one}",
    // Players moving between servers of a network were kicked for "invalid
    // chat signature" without this; it is the multi-server case.
    FABRIC_PROXY_HACK_MESSAGE_CHAIN: "true",
    // Lets mods such as LuckPerms see the player's UUID during login.
    FABRIC_PROXY_HACK_EARLY_SEND: "true",
  };
  if (g.plugins.length) env.MODS = g.plugins.join(",");
  const ownsProxyMod = g.modrinth.some((r) => refSlug(r) === "fabricproxy-lite");
  const pinned = fabricProxyLiteFor(g.version);
  const refs = [
    ...(ownsProxyMod || !pinned ? [] : [`fabricproxy-lite:${pinned}`]),
    ...g.modrinth,
  ];
  if (refs.length) {
    env.MODRINTH_PROJECTS = refs.join(",");
    env.MODRINTH_DOWNLOAD_DEPENDENCIES = "required";
  }
  return env;
}

/**
 * A NeoForge server behind any proxy.
 *
 * Proxy-Compatible-Forge implements all three forwarding modes, but reads its
 * settings only from config/proxy-compatible-forge.toml — so, like Paper, it
 * is patched on every start (renderNeoForgePatches), and `cloud apply` seeds
 * the file before the first boot because the patcher skips missing files.
 */
function neoforgeEnv(
  g: CloudConfig["groups"][string],
  usesSecret: boolean,
): Record<string, string> {
  const env: Record<string, string> = {
    PATCH_DEFINITIONS: "/patches",
    REPLACE_ENV_VARIABLE_PREFIX: "CFG_",
  };
  if (usesSecret) {
    env.CFG_FORWARDING_SECRET = "${FORWARDING_SECRET:?run `cloud apply` to generate one}";
  }
  if (g.plugins.length) env.MODS = g.plugins.join(",");
  const ownsProxyMod = g.modrinth.some((r) => refSlug(r) === "proxy-compatible-forge");
  const refs = [
    ...(ownsProxyMod ? [] : [`proxy-compatible-forge:${PROXY_COMPATIBLE_FORGE}`]),
    ...g.modrinth,
  ];
  env.MODRINTH_PROJECTS = refs.join(",");
  env.MODRINTH_DOWNLOAD_DEPENDENCIES = "required";
  return env;
}

function yamlValue(v: unknown): string {
  if (typeof v === "boolean" || typeof v === "number") return `"${v}"`;
  const s = String(v);
  if (s === "" || /[:#{}\[\],&*?|<>=!%@`"'\\]/.test(s) || /^\s|\s$/.test(s)) {
    return JSON.stringify(s);
  }
  return `"${s}"`;
}

function envBlock(env: Record<string, unknown>, indent: string): string {
  return Object.entries(env)
    .map(([k, v]) => `${indent}${k}: ${yamlValue(v)}`)
    .join("\n");
}

/**
 * Where a server's plugin directory lives on the host.
 *
 * Editing a plugin's config is the one reason people genuinely need to open a
 * server's files, and a named volume makes that impossible — which is most
 * servers, since `volume` is the right default on Docker Desktop and
 * replaceable groups never bind-mount at all. So this one directory is always
 * on the host, whatever the storage mode: `./data/<server>/plugins`, same
 * path for every server, nothing to look up.
 *
 * The world stays wherever `storage` says. That is the part that is slow
 * across the Docker Desktop filesystem bridge; a handful of YAML files is not.
 */
export function hostPluginDir(instance: string): string {
  return `data/${instance}/plugins`;
}

/**
 * The directory of a backend that lives on the host, whatever its storage:
 * plugins/ for a plugin server, config/ for Fabric — where mods keep the
 * files people edit. Same reasoning as hostPluginDir, different software.
 */
export function serverFilesDir(
  instance: string,
  software: string,
): { host: string; container: string } {
  return runsPlugins(software)
    ? { host: hostPluginDir(instance), container: "/data/plugins" }
    : { host: `data/${instance}/config`, container: "/data/config" };
}

/**
 * Host directories that must exist before `docker compose up`.
 *
 * Docker creates a missing bind source as root, which the itzg image then has
 * to chown. Creating them as the invoking user first keeps them editable
 * without sudo — the entire point of the directory being there.
 */
export function hostDirs(cfg: CloudConfig): string[] {
  const dirs = [hostPluginDir("proxy")];
  for (const [group, g] of Object.entries(cfg.groups)) {
    for (const instance of instanceNames(group, g.min)) {
      if (bindsWholeData(cfg, g)) dirs.push(`data/${instance}`);
      else dirs.push(serverFilesDir(instance, g.software).host);
    }
    // A declared template that does not exist on disk is the same trap: Docker
    // creates the missing bind source as an empty root-owned directory and the
    // server seeds nothing, with no error anywhere. Create it so there is
    // somewhere obvious to put the files.
    if (g.template) dirs.push(`templates/${g.template}`);
  }
  return dirs;
}

/**
 * Which host directories each container writes to, and as whom.
 *
 * The images run their server as uid/gid 1000 unless `UID`/`GID` in the
 * service's environment say otherwise, and a server must be able to write
 * where its files are bind-mounted. Templates are absent on purpose: they are
 * mounted read-only and only ever read.
 */
export function hostDirOwners(cfg: CloudConfig): { dir: string; uid: number; gid: number }[] {
  const id = (env: Record<string, string>) => ({
    uid: Number(env.UID ?? 1000),
    gid: Number(env.GID ?? 1000),
  });
  const out = [{ dir: hostPluginDir("proxy"), ...id(cfg.proxy.env) }];
  for (const [group, g] of Object.entries(cfg.groups)) {
    for (const instance of instanceNames(group, g.min)) {
      const dir = bindsWholeData(cfg, g)
        ? `data/${instance}`
        : serverFilesDir(instance, g.software).host;
      out.push({ dir, ...id(g.env) });
    }
  }
  return out;
}

/** True when the whole /data directory is a bind mount, not just plugins. */
function bindsWholeData(cfg: CloudConfig, g: CloudConfig["groups"][string]): boolean {
  return g.static && cfg.network.storage === "bind";
}

/** Instance names for a group: `lobby` alone, or `lobby-1`, `lobby-2`, ... */
export function instanceNames(group: string, min: number): string[] {
  if (min <= 1) return [group];
  return Array.from({ length: min }, (_, i) => `${group}-${i + 1}`);
}

export function renderCompose(cfg: CloudConfig): string {
  const lines: string[] = [GENERATED, "services:"];

  const wiring = wiringFor(cfg.network.forwarding);
  const allInstances: string[] = [];
  let fallbackInstance = "";
  for (const [name, g] of Object.entries(cfg.groups)) {
    const names = instanceNames(name, g.min);
    allInstances.push(...names);
    if (g.fallback) fallbackInstance = names[0];
  }

  // ---- proxy -------------------------------------------------------------
  const proxyEnv: Record<string, unknown> = {
    TYPE: cfg.proxy.software.toUpperCase(),
    MEMORY: cfg.proxy.memory,
    REPLACE_ENV_VARIABLES: "true",
    REPLACE_ENV_VARIABLE_PREFIX: "CFG_",
    CFG_MOTD: cfg.network.motd,
  };
  if (cfg.proxy.software === "velocity") {
    proxyEnv.VELOCITY_VERSION = cfg.proxy.version;
  } else {
    // The image's healthcheck reads velocity.toml's bind for Velocity, but
    // assumes BungeeCord's default 25577 for everything else — while our
    // config.yml binds 25565. Without this a BungeeCord proxy served players
    // happily and reported "unhealthy" forever.
    proxyEnv.SERVER_PORT = "25565";
  }
  // BungeeCord and Waterfall images track the latest build of their software,
  // so proxy.version pins Velocity only. See SPEC.md.
  // Velocity has BungeeGuard built in; BungeeCord and Waterfall need the jar.
  const proxyGuard =
    wiring.guard && cfg.proxy.software !== "velocity" ? [BUNGEEGUARD_JAR] : [];
  Object.assign(
    proxyEnv,
    pluginEnv(cfg.proxy, proxyHangarPlatform(cfg.proxy.software), proxyGuard),
  );
  if (wiring.usesSecret) {
    // Not read by anything in the proxy. It is here so that rotating the
    // secret changes the proxy's resolved environment, and Compose therefore
    // recreates it along with the backends. Without it the proxy kept the old
    // secret in memory — Velocity reads its secret file only at boot, and
    // BungeeGuard its token.yml — and rejected every login after a rotation.
    proxyEnv.CFG_FORWARDING_SECRET =
      "${FORWARDING_SECRET:?run `cloud apply` to generate one}";
  }
  Object.assign(proxyEnv, {
    CLOUD_NETWORK: cfg.network.name,
    CLOUD_INSTANCE: "proxy",
    CLOUD_SERVERS: allInstances.join(","),
  });
  // User-supplied env wins, exactly as it does for groups.
  Object.assign(proxyEnv, cfg.proxy.env);

  lines.push(`  proxy:`);
  lines.push(
    `    image: ${proxyImage(cfg.proxy.software, cfg.proxy.version, cfg.proxy.java, cfg.proxy.pin)}`,
  );
  lines.push(`    container_name: ${cfg.network.name}-proxy`);
  lines.push(`    restart: unless-stopped`);
  lines.push(
    `    mem_limit: ${containerLimitMiB(cfg.proxy.memory, cfg.proxy.memory_limit)}m`,
  );
  lines.push(`    environment:`);
  lines.push(envBlock(proxyEnv, "      "));
  lines.push(`    ports:`);
  lines.push(
    `      # The proxy is the ONLY service with published ports. Backends stay`,
  );
  lines.push(`      # on the internal network — see README, "No backend ports".`);
  lines.push(`      - "\${ENTRY_PORT:-${cfg.network.entry_port}}:25565"`);
  for (const mapping of cfg.proxy.ports) {
    lines.push(`      - "${mapping}"`);
  }
  lines.push(`    volumes:`);
  const proxyConfig = proxyConfigFile(cfg.proxy.software);
  lines.push(`      - ./${proxyConfig}:/config/${proxyConfig.split("/")[1]}:ro`);
  // Only Velocity reads a secret file. Under bungeeguard on BungeeCord the
  // token lives in the BungeeGuard plugin's own config instead.
  if (wiring.usesSecret && cfg.proxy.software === "velocity") {
    lines.push(`      - ./proxy/forwarding.secret:/config/forwarding.secret:ro`);
  }
  lines.push(`      - proxy-data:/server`);
  // See hostPluginDir: the proxy runs plugins too, and their configs are just
  // as much a thing you open by hand.
  lines.push(`      - ./${hostPluginDir("proxy")}:/server/plugins`);
  lines.push(`    networks: [cloud]`);
  lines.push("");

  // ---- backends ----------------------------------------------------------
  for (const [group, g] of Object.entries(cfg.groups)) {
    for (const instance of instanceNames(group, g.min)) {
      const env: Record<string, unknown> = {
        EULA: "TRUE",
        TYPE: g.software.toUpperCase(),
        VERSION: g.version,
        MEMORY: g.memory,
        SERVER_NAME: instance,
        // The proxy authenticates. The backend must not.
        ONLINE_MODE: "FALSE",
      };
      const plugins = runsPlugins(g.software);
      if (plugins) {
        env.PATCH_DEFINITIONS = "/patches";
        env.REPLACE_ENV_IN_PLACE = "true";
        env.REPLACE_ENV_VARIABLE_PREFIX = "CFG_";
        env.CFG_VELOCITY_ENABLED = String(wiring.velocityEnabled);
        // Must match the proxy's online-mode, NOT ONLINE_MODE above. They are
        // opposite switches: the backend does not authenticate, the proxy does.
        env.CFG_VELOCITY_ONLINE_MODE = String(cfg.network.online);
        // The legacy half of the same pair. Exactly one of the two is on.
        env.CFG_BUNGEE_ENABLED = String(wiring.bungeeEnabled);
        env.CFG_BUNGEE_ONLINE_MODE = String(
          wiring.bungeeEnabled && cfg.network.online,
        );
        if (wiring.usesSecret) {
          env.CFG_FORWARDING_SECRET =
            "${FORWARDING_SECRET:?run `cloud apply` to generate one}";
        }
        // Under bungeeguard the plugin is what checks the token; without it the
        // mode silently degrades to legacy. See BUNGEEGUARD_JAR.
        Object.assign(env, pluginEnv(g, "PAPER", wiring.guard ? [BUNGEEGUARD_JAR] : []));
      } else if (g.software === "fabric") {
        Object.assign(env, fabricEnv(g));
      } else {
        Object.assign(env, neoforgeEnv(g, wiring.usesSecret));
      }
      if (g.template) {
        // Copy the whole template tree into /data, so templates/<name>/ mirrors
        // the server directory: plugins/Foo/config.yml lands where you expect.
        // Without this the image would only copy into /data/config.
        env.COPY_CONFIG_DEST = "/data";
        // The template is authoritative: it is re-applied over every instance
        // on every start, so one edit in templates/<name>/ reaches all of them.
        // The image's default is the opposite (skip files that are newer in
        // the destination), which made a template a one-shot seed — edit it
        // later and nothing happened, silently. Files the template does not
        // contain, including the world, are left alone.
        env.SYNC_SKIP_NEWER_IN_DESTINATION = "false";
      }

      // Network awareness for plugins running ON the server. This is the
      // whole "cloud API": System.getenv("CLOUD_GROUP"). No jar to ship, no
      // version to match, nothing that can break on upgrade.
      Object.assign(env, {
        CLOUD_NETWORK: cfg.network.name,
        CLOUD_GROUP: group,
        CLOUD_INSTANCE: instance,
        CLOUD_INSTANCE_INDEX: String(instanceNames(group, g.min).indexOf(instance) + 1),
        CLOUD_GROUP_SIZE: String(g.min),
        CLOUD_STATIC: String(g.static),
        CLOUD_FALLBACK: fallbackInstance,
        CLOUD_GROUPS: Object.keys(cfg.groups).join(","),
        CLOUD_SERVERS: allInstances.join(","),
        CLOUD_PROXY: `${cfg.network.name}-proxy`,
      });

      // User-supplied env wins: an override must actually override.
      Object.assign(env, g.env);

      lines.push(`  ${instance}:`);
      lines.push(`    image: ${serverImage(g.version, g.java, g.pin)}`);
      lines.push(`    container_name: ${cfg.network.name}-${instance}`);
      lines.push(`    restart: unless-stopped`);
      // Heap plus headroom; see containerLimitMiB. Without a cap, one leaking
      // server can take the whole host down with it.
      lines.push(`    mem_limit: ${containerLimitMiB(g.memory, g.memory_limit)}m`);
      lines.push(`    environment:`);
      lines.push(envBlock(env, "      "));
      lines.push(`    expose:`);
      lines.push(`      - "25565"`);
      lines.push(`    volumes:`);
      // A static group keeps its world. Where that world lives is a config
      // choice, not a platform check — rendering stays a pure function of
      // cloud.toml so the same file produces the same output everywhere.
      const bind = bindsWholeData(cfg, g);
      lines.push(
        bind
          ? `      - ./data/${instance}:/data`
          : `      - ${instance}-data:/data`,
      );
      // When /data is a volume, bind the plugins directory (config/ for
      // Fabric) on its own so it stays reachable from the host. A
      // bind-mounted group already has it.
      if (!bind) {
        const files = serverFilesDir(instance, g.software);
        lines.push(`      - ./${files.host}:${files.container}`);
      }
      if (g.template) {
        // /config is the image's own seeding hook: its contents are copied
        // into COPY_CONFIG_DEST at startup. Mounting at /template did nothing
        // at all — the image has never known that path.
        lines.push(
          `      # templates/${g.template}/ owns these files. Edit them there, not in`,
        );
        lines.push(`      # ./data/${instance}/ — this copy is overwritten on every start.`);
        lines.push(`      - ./templates/${g.template}:/config:ro`);
      }
      // Each server type gets only the patches for its own files: Paper's
      // for Paper, Proxy-Compatible-Forge's for NeoForge, none for Fabric,
      // which takes its secret from the environment.
      if (plugins) lines.push(`      - ./proxy/patches:/patches:ro`);
      if (g.software === "neoforge") {
        lines.push(`      - ./proxy/patches/neoforge:/patches:ro`);
      }
      lines.push(`    networks: [cloud]`);
      lines.push("");
    }
  }

  lines.push("networks:");
  lines.push("  cloud:");
  lines.push("    driver: bridge");
  lines.push("");
  lines.push("volumes:");
  lines.push("  proxy-data:");
  for (const [group, g] of Object.entries(cfg.groups)) {
    // Only bind-mounted static groups skip a named volume.
    if (g.static && cfg.network.storage === "bind") continue;
    for (const instance of instanceNames(group, g.min)) {
      lines.push(`  ${instance}-data:`);
    }
  }

  return lines.join("\n") + "\n";
}
