import type { CloudConfig } from "../types.ts";
import { proxyConfigFile, wiringFor } from "./forwarding.ts";

const GENERATED =
  "# GENERATED by `cloud apply` — DO NOT EDIT.\n" +
  "# Source of truth is cloud.toml. Changes here are overwritten.\n";

/**
 * Java major version per Minecraft version.
 *
 * Getting this wrong produces UnsupportedClassVersionError with a class file
 * number rather than a Java version, which is why the mapping lives in one
 * place with the numbers written down:
 *   class 52=Java 8, 61=17, 65=21, 69=25.
 */
export function javaFor(mcVersion: string): number {
  const [major, minor] = mcVersion.split(".").map(Number);
  // Minecraft moved to year-based versioning (26.1). Those need Java 25.
  if (major >= 26) return 25;
  if (major !== 1) return 25;
  if (minor >= 21) return 21;
  if (minor >= 18) return 17;
  if (minor >= 17) return 16;
  return 8;
}

/**
 * Velocity 4.x requires Java 25; 3.x runs on 17+. "latest" resolves to a
 * 4.0.0 snapshot, so an unpinned proxy silently needs a newer runtime than
 * the image provides.
 */
export function proxyJavaFor(software: string, version: string): number {
  if (software !== "velocity") return 17;
  if (/^4\./.test(version)) return 25;
  if (version === "latest") return 25; // latest is currently a 4.x snapshot
  return 21;
}

function proxyImage(software: string, version: string, override?: number): string {
  // Velocity/Bungee/Waterfall all live in itzg/mc-proxy, selected by TYPE.
  // This is NOT the same image as the backends.
  return `itzg/mc-proxy:java${override ?? proxyJavaFor(software, version)}`;
}

function serverImage(mcVersion: string, override?: number): string {
  return `itzg/minecraft-server:java${override ?? javaFor(mcVersion)}`;
}

function yamlValue(v: unknown): string {
  if (typeof v === "boolean" || typeof v === "number") return `"${v}"`;
  const s = String(v);
  if (s === "" || /[:#{}\[\],&*?|<>=!%@`"'\\]/.test(s) || /^\s|\s$/.test(s)) {
    return JSON.stringify(s);
  }
  return `"${s}"`;
}

function envBlock(env: Record<string, unknown>, indent: string): string {
  return Object.entries(env)
    .map(([k, v]) => `${indent}${k}: ${yamlValue(v)}`)
    .join("\n");
}

/**
 * Where a server's plugin directory lives on the host.
 *
 * Editing a plugin's config is the one reason people genuinely need to open a
 * server's files, and a named volume makes that impossible — which is most
 * servers, since `volume` is the right default on Docker Desktop and
 * replaceable groups never bind-mount at all. So this one directory is always
 * on the host, whatever the storage mode: `./data/<server>/plugins`, same
 * path for every server, nothing to look up.
 *
 * The world stays wherever `storage` says. That is the part that is slow
 * across the Docker Desktop filesystem bridge; a handful of YAML files is not.
 */
export function hostPluginDir(instance: string): string {
  return `data/${instance}/plugins`;
}

/**
 * Host directories that must exist before `docker compose up`.
 *
 * Docker creates a missing bind source as root, which the itzg image then has
 * to chown. Creating them as the invoking user first keeps them editable
 * without sudo — the entire point of the directory being there.
 */
export function hostDirs(cfg: CloudConfig): string[] {
  const dirs = [hostPluginDir("proxy")];
  for (const [group, g] of Object.entries(cfg.groups)) {
    for (const instance of instanceNames(group, g.min)) {
      if (bindsWholeData(cfg, g)) dirs.push(`data/${instance}`);
      else dirs.push(hostPluginDir(instance));
    }
    // A declared template that does not exist on disk is the same trap: Docker
    // creates the missing bind source as an empty root-owned directory and the
    // server seeds nothing, with no error anywhere. Create it so there is
    // somewhere obvious to put the files.
    if (g.template) dirs.push(`templates/${g.template}`);
  }
  return dirs;
}

/** True when the whole /data directory is a bind mount, not just plugins. */
function bindsWholeData(cfg: CloudConfig, g: CloudConfig["groups"][string]): boolean {
  return g.static && cfg.network.storage === "bind";
}

/** Instance names for a group: `lobby` alone, or `lobby-1`, `lobby-2`, ... */
export function instanceNames(group: string, min: number): string[] {
  if (min <= 1) return [group];
  return Array.from({ length: min }, (_, i) => `${group}-${i + 1}`);
}

export function renderCompose(cfg: CloudConfig): string {
  const lines: string[] = [GENERATED, "services:"];

  const wiring = wiringFor(cfg.network.forwarding);
  const patched = cfg.network.forwarding !== "none";
  const allInstances: string[] = [];
  let fallbackInstance = "";
  for (const [name, g] of Object.entries(cfg.groups)) {
    const names = instanceNames(name, g.min);
    allInstances.push(...names);
    if (g.fallback) fallbackInstance = names[0];
  }

  // ---- proxy -------------------------------------------------------------
  const proxyEnv: Record<string, unknown> = {
    TYPE: cfg.proxy.software.toUpperCase(),
    MEMORY: cfg.proxy.memory,
    REPLACE_ENV_VARIABLES: "true",
    REPLACE_ENV_VARIABLE_PREFIX: "CFG_",
    CFG_MOTD: cfg.network.motd,
  };
  if (cfg.proxy.software === "velocity") {
    proxyEnv.VELOCITY_VERSION = cfg.proxy.version;
  }
  // BungeeCord and Waterfall images track the latest build of their software,
  // so proxy.version pins Velocity only. See SPEC.md.
  if (cfg.proxy.plugins.length) {
    proxyEnv.PLUGINS = cfg.proxy.plugins.join(",");
  }
  Object.assign(proxyEnv, {
    CLOUD_NETWORK: cfg.network.name,
    CLOUD_INSTANCE: "proxy",
    CLOUD_SERVERS: allInstances.join(","),
  });
  // User-supplied env wins, exactly as it does for groups.
  Object.assign(proxyEnv, cfg.proxy.env);

  lines.push(`  proxy:`);
  lines.push(
    `    image: ${proxyImage(cfg.proxy.software, cfg.proxy.version, cfg.proxy.java)}`,
  );
  lines.push(`    container_name: ${cfg.network.name}-proxy`);
  lines.push(`    restart: unless-stopped`);
  lines.push(`    environment:`);
  lines.push(envBlock(proxyEnv, "      "));
  lines.push(`    ports:`);
  lines.push(
    `      # The proxy is the ONLY service with published ports. Backends stay`,
  );
  lines.push(`      # on the internal network — see README, "No backend ports".`);
  lines.push(`      - "\${ENTRY_PORT:-${cfg.network.entry_port}}:25565"`);
  for (const mapping of cfg.proxy.ports) {
    lines.push(`      - "${mapping}"`);
  }
  lines.push(`    volumes:`);
  const proxyConfig = proxyConfigFile(cfg.proxy.software);
  lines.push(`      - ./${proxyConfig}:/config/${proxyConfig.split("/")[1]}:ro`);
  // Only Velocity reads a secret file. Under bungeeguard on BungeeCord the
  // token lives in the BungeeGuard plugin's own config instead.
  if (wiring.usesSecret && cfg.proxy.software === "velocity") {
    lines.push(`      - ./proxy/forwarding.secret:/config/forwarding.secret:ro`);
  }
  lines.push(`      - proxy-data:/server`);
  // See hostPluginDir: the proxy runs plugins too, and their configs are just
  // as much a thing you open by hand.
  lines.push(`      - ./${hostPluginDir("proxy")}:/server/plugins`);
  lines.push(`    networks: [cloud]`);
  lines.push("");

  // ---- backends ----------------------------------------------------------
  for (const [group, g] of Object.entries(cfg.groups)) {
    for (const instance of instanceNames(group, g.min)) {
      const env: Record<string, unknown> = {
        EULA: "TRUE",
        TYPE: g.software.toUpperCase(),
        VERSION: g.version,
        MEMORY: g.memory,
        SERVER_NAME: instance,
        // The proxy authenticates. The backend must not.
        ONLINE_MODE: "FALSE",
      };
      if (patched) {
        env.PATCH_DEFINITIONS = "/patches";
        env.REPLACE_ENV_IN_PLACE = "true";
        env.REPLACE_ENV_VARIABLE_PREFIX = "CFG_";
        env.CFG_VELOCITY_ENABLED = String(wiring.velocityEnabled);
        // Must match the proxy's online-mode, NOT ONLINE_MODE above. They are
        // opposite switches: the backend does not authenticate, the proxy does.
        env.CFG_VELOCITY_ONLINE_MODE = String(cfg.network.online);
        // The legacy half of the same pair. Exactly one of the two is on.
        env.CFG_BUNGEE_ENABLED = String(wiring.bungeeEnabled);
        env.CFG_BUNGEE_ONLINE_MODE = String(
          wiring.bungeeEnabled && cfg.network.online,
        );
        if (wiring.usesSecret) {
          env.CFG_FORWARDING_SECRET =
            "${FORWARDING_SECRET:?run `cloud apply` to generate one}";
        }
      }
      if (g.plugins.length) env.PLUGINS = g.plugins.join(",");
      if (g.template) {
        // Copy the whole template tree into /data, so templates/<name>/ mirrors
        // the server directory: plugins/Foo/config.yml lands where you expect.
        // Without this the image would only copy into /data/config.
        env.COPY_CONFIG_DEST = "/data";
        // The template is authoritative: it is re-applied over every instance
        // on every start, so one edit in templates/<name>/ reaches all of them.
        // The image's default is the opposite (skip files that are newer in
        // the destination), which made a template a one-shot seed — edit it
        // later and nothing happened, silently. Files the template does not
        // contain, including the world, are left alone.
        env.SYNC_SKIP_NEWER_IN_DESTINATION = "false";
      }

      // Network awareness for plugins running ON the server. This is the
      // whole "cloud API": System.getenv("CLOUD_GROUP"). No jar to ship, no
      // version to match, nothing that can break on upgrade.
      Object.assign(env, {
        CLOUD_NETWORK: cfg.network.name,
        CLOUD_GROUP: group,
        CLOUD_INSTANCE: instance,
        CLOUD_INSTANCE_INDEX: String(instanceNames(group, g.min).indexOf(instance) + 1),
        CLOUD_GROUP_SIZE: String(g.min),
        CLOUD_STATIC: String(g.static),
        CLOUD_FALLBACK: fallbackInstance,
        CLOUD_GROUPS: Object.keys(cfg.groups).join(","),
        CLOUD_SERVERS: allInstances.join(","),
        CLOUD_PROXY: `${cfg.network.name}-proxy`,
      });

      // User-supplied env wins: an override must actually override.
      Object.assign(env, g.env);

      lines.push(`  ${instance}:`);
      lines.push(`    image: ${serverImage(g.version, g.java)}`);
      lines.push(`    container_name: ${cfg.network.name}-${instance}`);
      lines.push(`    restart: unless-stopped`);
      lines.push(`    environment:`);
      lines.push(envBlock(env, "      "));
      lines.push(`    expose:`);
      lines.push(`      - "25565"`);
      lines.push(`    volumes:`);
      // A static group keeps its world. Where that world lives is a config
      // choice, not a platform check — rendering stays a pure function of
      // cloud.toml so the same file produces the same output everywhere.
      const bind = bindsWholeData(cfg, g);
      lines.push(
        bind
          ? `      - ./data/${instance}:/data`
          : `      - ${instance}-data:/data`,
      );
      // When /data is a volume, bind the plugins directory on its own so it
      // stays reachable from the host. A bind-mounted group already has it.
      if (!bind) {
        lines.push(`      - ./${hostPluginDir(instance)}:/data/plugins`);
      }
      if (g.template) {
        // /config is the image's own seeding hook: its contents are copied
        // into COPY_CONFIG_DEST at startup. Mounting at /template did nothing
        // at all — the image has never known that path.
        lines.push(
          `      # templates/${g.template}/ owns these files. Edit them there, not in`,
        );
        lines.push(`      # ./data/${instance}/ — this copy is overwritten on every start.`);
        lines.push(`      - ./templates/${g.template}:/config:ro`);
      }
      if (patched) lines.push(`      - ./proxy/patches:/patches:ro`);
      lines.push(`    networks: [cloud]`);
      lines.push("");
    }
  }

  lines.push("networks:");
  lines.push("  cloud:");
  lines.push("    driver: bridge");
  lines.push("");
  lines.push("volumes:");
  lines.push("  proxy-data:");
  for (const [group, g] of Object.entries(cfg.groups)) {
    // Only bind-mounted static groups skip a named volume.
    if (g.static && cfg.network.storage === "bind") continue;
    for (const instance of instanceNames(group, g.min)) {
      lines.push(`  ${instance}-data:`);
    }
  }

  return lines.join("\n") + "\n";
}
