import type { CloudConfig } from "../types.ts";
import { instanceNames } from "./compose.ts";
import { wiringFor } from "./forwarding.ts";

/**
 * Every instance as [name, host:port], plus where players land.
 *
 * `fallbacks` is every instance of the fallback group, not just the first.
 * Both proxies treat this as an ordered list: they walk it until one accepts
 * the connection. That means it is failover, not load balancing — everyone
 * still joins on the first entry — but it is what lets a player whose backend
 * goes down land on a sibling instead of being disconnected. With one entry,
 * restarting that entry drops the very players it was supposed to catch.
 */
function topology(cfg: CloudConfig): {
  servers: [string, string][];
  fallbacks: string[];
} {
  const servers: [string, string][] = [];
  let fallbacks: string[] = [];
  for (const [group, g] of Object.entries(cfg.groups)) {
    const names = instanceNames(group, g.min);
    for (const instance of names) {
      // Container name resolves via Docker's embedded DNS.
      servers.push([instance, `${cfg.network.name}-${instance}:25565`]);
    }
    if (g.fallback) fallbacks = names;
  }
  return { servers, fallbacks };
}

export function renderVelocityToml(cfg: CloudConfig): string {
  const { servers: topo, fallbacks } = topology(cfg);
  const servers = topo.map(([name, addr]) => `${name} = "${addr}"`);
  // Legacy forwarding carries no secret at all: backends trust the proxy's
  // word purely because nothing outside the Docker network can reach them.
  const secretLine = wiringFor(cfg.network.forwarding).usesSecret
    ? 'forwarding-secret-file = "forwarding.secret"'
    : "# legacy forwarding: no secret to share";

  return `# GENERATED by \`cloud apply\` — DO NOT EDIT.
config-version = "2.7"

# Velocity always binds 25565 inside its container. The host-side port is
# set by the compose \`ports:\` mapping.
bind = "0.0.0.0:25565"

motd = "\${CFG_MOTD}"
show-max-players = 100

online-mode = ${cfg.network.online}
force-key-authentication = true
prevent-client-proxy-connections = false

player-info-forwarding-mode = "${cfg.network.forwarding}"
${secretLine}

announce-forge = false

[servers]
${servers.join("\n")}

# Tried in order: the first reachable entry is where players land, and where
# they are sent when a backend dies under them. Every instance of the fallback
# group is listed so that restarting one moves its players to a sibling rather
# than disconnecting them. Ordered, not balanced — everyone still joins on the
# first entry.
try = [${fallbacks.map((f) => `"${f}"`).join(", ")}]

[forced-hosts]

[advanced]
compression-threshold = 256
compression-level = -1
login-ratelimit = 3000
connection-timeout = 5000
read-timeout = 30000
haproxy-protocol = false
tcp-fast-open = false
failover-on-unexpected-server-disconnect = true

[query]
enabled = false
`;
}

/**
 * BungeeCord and Waterfall read config.yml, not velocity.toml. Rendering the
 * wrong one produced a proxy that started, listened, and refused every login —
 * so the file is chosen from proxy.software in exactly one place
 * (`proxyConfigFile`) and both renderers exist.
 *
 * `ip_forward` is BungeeCord's equivalent of forwarding: on, the backend
 * receives the player's real IP and UUID in the handshake. It is required for
 * both legacy and bungeeguard. Modern forwarding does not exist here at all,
 * which the schema rejects rather than letting it fail at login time.
 */
export function renderBungeeConfig(cfg: CloudConfig): string {
  const { servers: topo, fallbacks } = topology(cfg);
  const wiring = wiringFor(cfg.network.forwarding);
  // BungeeGuard's token lives in the plugin's own files, not in this one.
  // Say where, so nobody goes looking for it here.
  const guidance = wiring.guard
    ? [
        "# bungeeguard: the BungeeGuard plugin is installed on the proxy and every",
        "# backend by `cloud apply`, and its token is the forwarding secret —",
        "# data/proxy/plugins/BungeeGuard/token.yml here, allowed-tokens on the",
        "# backends. Rotate with `cloud apply --rotate-secret`.",
        "",
      ].join("\n")
    : "";

  const priorities = fallbacks.map((f) => `      - ${f}`).join("\n");

  const servers = topo
    .flatMap(([name, addr]) => [
      `  ${name}:`,
      `    address: ${addr}`,
      `    motd: ${JSON.stringify(name)}`,
      `    restricted: false`,
    ])
    .join("\n");

  return `# GENERATED by \`cloud apply\` — DO NOT EDIT.
# Source of truth is cloud.toml. Changes here are overwritten.

listeners:
  # The proxy always binds 25565 inside its container. The host-side port is
  # set by the compose \`ports:\` mapping.
  - host: 0.0.0.0:25565
    motd: '\${CFG_MOTD}'
    max_players: 100
    # Tried in order: the first reachable entry is where players land, and
    # where they are sent when a backend dies under them. Every instance is
    # listed so restarting one moves its players to a sibling.
    priorities:
${priorities}
    force_default_server: false
    bind_local_address: true
    ping_passthrough: false
    query_enabled: false
    query_port: 25577
    tab_list: GLOBAL_PING
    proxy_protocol: false

servers:
${servers}

# BungeeCord's forwarding switch. Backends read the player's real identity out
# of the handshake, which is why they must not be reachable directly.
ip_forward: true
online_mode: ${cfg.network.online}
prevent_proxy_connections: false
forge_support: false

network_compression_threshold: 256
connection_throttle: -1
timeout: 30000
player_limit: -1

groups: {}
permissions: {}
disabled_commands: []
${guidance}`;
}

/**
 * Paper writes config/paper-global.yml on first boot. itzg's patch mechanism
 * edits it after generation and before the JVM starts, which is the only
 * reliable window.
 *
 * PATCH_DEFINITIONS points at a directory, and each file in it is ONE patch
 * set whose top level is `file` + `ops`. There is no `patches` array wrapper
 * in this form — that shape is rejected with "unrecognized field patches".
 * Two target files therefore mean two definition files.
 */
/**
 * Proxy-Compatible-Forge's settings for NeoForge servers, if there are any.
 *
 * $put on the [forwarding] table, so each key is added when the file is the
 * near-empty seed and replaced when NeoForge has written it out in full. The
 * mode follows the network's, from the one table in forwarding.ts.
 */
export function renderNeoForgePatches(cfg: CloudConfig): Record<string, string> {
  if (!Object.values(cfg.groups).some((g) => g.software === "neoforge")) return {};
  const wiring = wiringFor(cfg.network.forwarding);
  const put = (key: string, value: string, type?: string) => ({
    $put: { path: "$.forwarding", key, value, ...(type ? { "value-type": type } : {}) },
  });
  const ops = [put("enabled", "true", "bool"), put("mode", wiring.pcfMode)];
  if (wiring.usesSecret) ops.push(put("secret", "${CFG_FORWARDING_SECRET}"));
  return {
    "proxy-compatible-forge.json":
      JSON.stringify(
        { file: "/data/config/proxy-compatible-forge.toml", "file-format": "toml", ops },
        null,
        2,
      ) + "\n",
  };
}

export function renderPaperPatches(cfg: CloudConfig): Record<string, string> {
  const wiring = wiringFor(cfg.network.forwarding);
  // Every mode enables exactly one of the two; a mode that enables neither
  // has nothing to patch.
  if (!wiring.velocityEnabled && !wiring.bungeeEnabled) return {};

  const velocityOps: Record<string, unknown>[] = [
    {
      $set: {
        path: "$.proxies.velocity.enabled",
        value: "${CFG_VELOCITY_ENABLED}",
        "value-type": "bool",
      },
    },
    {
      $set: {
        path: "$.proxies.velocity.online-mode",
        value: "${CFG_VELOCITY_ONLINE_MODE}",
        "value-type": "bool",
      },
    },
  ];
  // Only modern forwarding puts the secret in paper-global.yml. Under
  // bungeeguard the same token belongs to the plugin, not to Paper — writing
  // it here would be harmless but misleading, and it would put the secret in
  // one more place that has to be rotated.
  if (wiring.velocityEnabled && wiring.usesSecret) {
    velocityOps.push({
      $set: {
        path: "$.proxies.velocity.secret",
        value: "${CFG_FORWARDING_SECRET}",
      },
    });
  }

  const paperGlobal = {
    file: "/data/config/paper-global.yml",
    ops: [
      ...velocityOps,
      {
        // The other half of the pair. Exactly one of velocity/bungee-cord is
        // on; both on, or both off, breaks login or skins respectively.
        $set: {
          path: "$.proxies.bungee-cord.online-mode",
          value: "${CFG_BUNGEE_ONLINE_MODE}",
          "value-type": "bool",
        },
      },
    ],
  };

  const spigot = {
    file: "/data/spigot.yml",
    ops: [
      {
        // false under modern forwarding, true under legacy/bungeeguard.
        $set: {
          path: "$.settings.bungeecord",
          value: "${CFG_BUNGEE_ENABLED}",
          "value-type": "bool",
        },
      },
    ],
  };

  const patches: Record<string, string> = {
    "paper-global.json": JSON.stringify(paperGlobal, null, 2) + "\n",
    "spigot.json": JSON.stringify(spigot, null, 2) + "\n",
  };

  if (wiring.guard) {
    // Replaces the whole list on every start, so a rotated secret reaches
    // every backend and the plugin's placeholder tokens never survive. $put
    // rather than $set: it adds the key when a template supplied a config
    // without it, where $set would find no path to replace. The value is a
    // string because the patcher only interpolates strings; "list of string"
    // turns it into a one-element list afterwards.
    //
    // The patcher skips a file that does not exist, and BungeeGuard writes
    // its config only after the patches have run — so `cloud apply` seeds the
    // file on the host first (seedBungeeGuard). Without that, the first boot
    // runs on the plugin's defaults and rejects every login.
    patches["bungeeguard.json"] =
      JSON.stringify(
        {
          file: "/data/plugins/BungeeGuard/config.yml",
          ops: [
            {
              $put: {
                path: "$",
                key: "allowed-tokens",
                value: "${CFG_FORWARDING_SECRET}",
                "value-type": "list of string",
              },
            },
          ],
        },
        null,
        2,
      ) + "\n";
  }

  return patches;
}
