#!/bin/sh
# Prints the CHANGELOG.md section for one version — the text of its GitHub
# release. Fails if there is none, so a release cannot go out without notes.
#
#   sh scripts/release-notes.sh 0.2.1      (a leading "v" is fine too)
#
# The section runs from "## 0.2.1" to the next "## " heading. Release notes
# used to be generated by GitHub from pull requests; this repository merges
# none, so a release said nothing but "Full Changelog" — three times, once per
# job that touched it.
set -eu
version="${1#v}"
notes=$(awk -v v="$version" '
  $1 == "##" && ($2 == v || $2 == "v" v) { on = 1; next }
  on && /^## / { exit }
  on { print }
' CHANGELOG.md | sed '/./,$!d')
if [ -z "$notes" ]; then
  echo "CHANGELOG.md has no \"## $version\" section. Add one, commit, then tag." >&2
  exit 1
fi
printf '%s\n' "$notes"
